In [ ]:
# ============================================================
# EXP 10: Iris Flower Classification
# ============================================================

# ============================================================
# STEP 1: Import Libraries
# ============================================================
import pandas as pd
import numpy as np

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [ ]:
# ============================================================
# STEP 2: Load Dataset
# ============================================================
iris = load_iris()

X = iris.data
y = iris.target

# Optional: Convert to DataFrame for clarity
df = pd.DataFrame(X, columns=iris.feature_names)
df['target'] = y

print("Dataset Shape:", df.shape)

Dataset Shape: (150, 5)


In [ ]:
# ============================================================
# STEP 3: Data Preprocessing
# ============================================================
# No missing values in Iris dataset
# Features and target already separated

In [ ]:
# ============================================================
# STEP 4: Train-Test Split
# ============================================================
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)


In [ ]:
# ============================================================
# STEP 5: Define Pipelines (Scaling + Model)
# ============================================================
pipelines = {
    "Logistic Regression": Pipeline([
        ("scaler", StandardScaler()),
        ("model", LogisticRegression(max_iter=200))
    ]),

    "Random Forest": Pipeline([
        ("scaler", StandardScaler()),
        ("model", RandomForestClassifier(n_estimators=100))
    ]),

    "SVM": Pipeline([
        ("scaler", StandardScaler()),
        ("model", SVC())
    ]),

    "KNN": Pipeline([
        ("scaler", StandardScaler()),
        ("model", KNeighborsClassifier())
    ]),

    "Decision Tree": Pipeline([
        ("scaler", StandardScaler()),
        ("model", DecisionTreeClassifier())
    ])
}

In [ ]:
# ============================================================
# STEP 6 & 7: Train and Predict
# ============================================================
results = {}

for name, pipe in pipelines.items():
    print("\n==============================")
    print(f"Model: {name}")
    print("==============================")

    pipe.fit(X_train, y_train)
    y_pred = pipe.predict(X_test)

    acc = accuracy_score(y_test, y_pred)
    results[name] = acc

    print("Accuracy:", round(acc, 4))

    print("\nClassification Report:")
    print(classification_report(y_test, y_pred))

    print("Confusion Matrix:")
    print(confusion_matrix(y_test, y_pred))


Model: Logistic Regression
Accuracy: 1.0

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

Model: Random Forest
Accuracy: 1.0

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

M

In [ ]:
# ============================================================
# STEP 8: Model Comparison
# ============================================================
print("\n==============================")
print("Final Model Comparison")
print("==============================")

for model, acc in results.items():
    print(f"{model}: {acc:.4f}")

best_model = max(results, key=results.get)
print("\nBest Performing Model:", best_model)


Final Model Comparison
Logistic Regression: 1.0000
Random Forest: 1.0000
SVM: 1.0000
KNN: 1.0000
Decision Tree: 1.0000

Best Performing Model: Logistic Regression
